const LANGS = {
  bubble: {
    js: {
      code: [
        "const n = ARR.length;",
        "let cmp = 0, swp = 0, wrt = 0;",
        "const a = ARR.slice();                               // 复制一份，不改动原数组",
        "const sorted = new Set();                            // 已排定的位置",
        "",
        "function swap(i, j) {                                // 交换两个元素",
        "  const t = a[i];",
        "  a[i] = a[j];",
        "  a[j] = t;",
        "}",
        "",
        "for (let pass = 0; pass < n - 1; pass++) {            // 每一轮把最大值送到右端",
        "  let swapped = false;                               // 本轮是否发生过交换",
        "  for (let i = 0; i < n - 1 - pass; i++) {",
        "    cmp++;                                           // 比较 a[i] 与 a[i+1]",
        "    if (a[i] > a[i + 1]) {                           // 逆序 → 交换",
        "      const t = a[i]; a[i] = a[i + 1]; a[i + 1] = t;",
        "      swp++; wrt += 2; swapped = true;",
        "    }",
        "  }",
        "  sorted.add(n - 1 - pass);                          // 本轮最大值已经就位",
        "  if (!swapped) break;                               // 提前退出：整轮无交换即已有序",
        "}",
        "report(a, n, cmp, swp, wrt);                         // 交给动画播放",
      ],
      steps: {
        swap: 17,
        mark: 21,
      },
    },
    py: {
      code: [
        "n = len(ARR)",
        "a = list(ARR)                                        # 复制一份，不改动原数组",
        "cmp = swp = wrt = 0",
        "sorted_pos = set()                                   # 已排定的位置",
        "",
        "def swap(i, j):",
        "    a[i], a[j] = a[j], a[i]",
        "",
        "for p in range(n - 1):                               # 每一轮把最大值送到右端",
        "    swapped = False                                  # 本轮是否发生过交换",
        "    for i in range(n - 1 - p):",
        "        cmp += 1                                     # 比较 a[i] 与 a[i+1]",
        "        if a[i] > a[i + 1]:                          # 逆序 → 交换",
        "            a[i], a[i + 1] = a[i + 1], a[i]",
        "            swp += 1; wrt += 2; swapped = True",
        "    sorted_pos.add(n - 1 - p)                        # 本轮最大值已经就位",
        "    if not swapped:                                  # 提前退出：整轮无交换即已有序",
        "        break",
        "report(a, cmp, swp, wrt)",
      ],
      steps: {
        swap: 14,
        mark: 16,
      },
    },
    c: {
      code: [
        "int n = ARR[0];",
        "int a[MAX];",
        "for (int i = 0; i < n; i++) a[i] = ARR[i + 1];",
        "int cmp = 0, swp = 0, wrt = 0;",
        "",
        "static void swap(int i, int j){                      /* 交换两个元素 */",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "static void pos_report(int i){                       /* 动画用的位置标记 */",
        '    printf("pos %d\\n", i);',
        "}",
        "",
        "for (int pass = 0; pass < n - 1; pass++) {           /* 每一轮把最大值送到右端 */",
        "    int swapped = 0;                                 /* 本轮是否发生过交换 */",
        "    for (int i = 0; i < n - 1 - pass; i++) {",
        "        cmp++;                                       /* 比较 a[i] 与 a[i+1] */",
        "        if (a[i] > a[i + 1]) {                       /* 逆序 → 交换 */",
        "            int t = a[i]; a[i] = a[i + 1]; a[i + 1] = t;",
        "            swp++; wrt += 2; swapped = 1;",
        "        }",
        "    }",
        '    printf("pos %d\\n", n - 1 - pass);               /* 本轮最大值已经就位 */',
        "    if (!swapped) break;                             /* 提前退出：整轮无交换即已有序 */",
        "}",
        'printf("%d %d %d\\n", cmp, swp, wrt);                /* 交给动画播放 */',
      ],
      steps: {
        swap: 21,
        mark: 25,
      },
    },
    java: {
      code: [
        "static void swap(int[] a, int i, int j){              // 交换两个元素",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "public static void main(String[] args){",
        "    int n = ARR.length;",
        "    int[] a = ARR.clone();                           // 复制一份",
        "",
        "    for (int pass = 0; pass < n - 1; pass++) {        // 每一轮把最大值送到右端",
        "        boolean swapped = false;                      // 本轮是否发生过交换",
        "        for (int i = 0; i < n - 1 - pass; i++) {",
        "            cmp++;                                    // 比较 a[i] 与 a[i+1]",
        "            if (a[i] > a[i + 1]) {                    // 逆序 → 交换",
        "                int t = a[i];",
        "                a[i] = a[i + 1];",
        "                a[i + 1] = t;",
        "                swp++; wrt += 2; swapped = true;",
        "            }",
        "        }",
        "        sortedPos.add(n - 1 - pass);                  // 本轮最大值已经就位",
        "        if (!swapped) break;                          // 提前退出：整轮无交换即已有序",
        "    }",
        "    report(a, n, cmp, swp, wrt);  // 交给动画播放",
      ],
      steps: {
        swap: 16,
        mark: 22,
      },
    },
  },
  insertion: {
    js: {
      code: [
        "const n = ARR.length;",
        "let cmp = 0, swp = 0, wrt = 0;",
        "const a = ARR.slice();                               // 复制一份，不改动原数组",
        "const sorted = new Set();                            // 已排定的位置",
        "",
        "function swap(i, j) {                                // 交换两个元素",
        "  const t = a[i];",
        "  a[i] = a[j];",
        "  a[j] = t;",
        "}",
        "",
        "for (let i = 1; i < n; i++) {",
        "  let j = i;                                         // 把 a[i] 向左挪到正确位置",
        "  while (j > 0) {",
        "    cmp++;                                           // 与左边相邻元素比较",
        "    if (a[j - 1] > a[j]) {                           // 比它大就交换",
        "      const t = a[j]; a[j] = a[j - 1]; a[j - 1] = t;",
        "      swp++; wrt += 2;",
        "      j--;",
        "    } else break;                                    // 已到正确位置",
        "  }",
        "  if (j === 0) wrt += 0;                             // 插入到位",
        "}",
        "report(a, n, cmp, swp, wrt);",
      ],
      steps: {
        key: 13,
        shift: 17,
        place: 22,
      },
    },
    py: {
      code: [
        "n = len(ARR)",
        "a = list(ARR)                                        # 复制一份，不改动原数组",
        "cmp = swp = wrt = 0",
        "sorted_pos = set()                                   # 已排定的位置",
        "",
        "def swap(i, j):",
        "    a[i], a[j] = a[j], a[i]",
        "",
        "for i in range(1, n):",
        "    j = i                                        # 把 a[i] 向左挪到正确位置",
        "    while j > 0:",
        "        cmp += 1                                 # 与左边相邻元素比较",
        "        if a[j - 1] > a[j]:                      # 比它大就交换",
        "            a[j - 1], a[j] = a[j], a[j - 1]",
        "            swp += 1; wrt += 2",
        "            j -= 1",
        "        else:",
        "            break                                # 已到正确位置",
        "    if j == 0: wrt += 0                          # 插入到位",
        "report(a, cmp, swp, wrt)",
      ],
      steps: {
        key: 10,
        shift: 14,
        place: 19,
      },
    },
    c: {
      code: [
        "int n = ARR[0];",
        "int a[MAX];",
        "for (int i = 0; i < n; i++) a[i] = ARR[i + 1];",
        "int cmp = 0, swp = 0, wrt = 0;",
        "",
        "static void swap(int i, int j){                      /* 交换两个元素 */",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "static void pos_report(int i){                       /* 动画用的位置标记 */",
        '    printf("pos %d\\n", i);',
        "}",
        "",
        "for (int i = 1; i < n; i++) {",
        "    int j = i;                                  /* 把 a[i] 向左挪到正确位置 */",
        "    while (j > 0) {",
        "        cmp++;                                  /* 与左边相邻元素比较 */",
        "        if (a[j - 1] > a[j]) {                  /* 比它大就交换 */",
        "            swap(j - 1, j);",
        "            swp++; wrt += 2;",
        "            j--;",
        "        } else break;                           /* 已到正确位置 */",
        "    }",
        "    if (j == 0) wrt += 0;                       /* 插入到位 */",
        "}",
        'printf("%d %d %d\\n", cmp, swp, wrt);',
      ],
      steps: {
        key: 17,
        shift: 21,
        place: 26,
      },
    },
    java: {
      code: [
        "static void swap(int[] a, int i, int j){              // 交换两个元素",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "public static void main(String[] args){",
        "    int n = ARR.length;",
        "    int[] a = ARR.clone();                           // 复制一份",
        "",
        "    for (int i = 1; i < n; i++) {",
        "        int j = i;                              // 把 a[i] 向左挪到正确位置",
        "        while (j > 0) {",
        "            cmp++;                              // 与左边相邻元素比较",
        "            if (a[j - 1] > a[j]) {              // 比它大就交换",
        "                swap(a, j - 1, j);",
        "                swp++; wrt += 2;",
        "                j--;",
        "            } else break;                       // 已到正确位置",
        "        }",
        "        if (j == 0) wrt += 0;                   // 插入到位",
        "    }",
        "    report(a, n, cmp, swp, wrt);",
      ],
      steps: {
        key: 12,
        shift: 16,
        place: 21,
      },
    },
  },
  selection: {
    js: {
      code: [
        "const n = ARR.length;",
        "let cmp = 0, swp = 0, wrt = 0;",
        "const a = ARR.slice();                               // 复制一份，不改动原数组",
        "const sorted = new Set();                            // 已排定的位置",
        "",
        "function swap(i, j) {                                // 交换两个元素",
        "  const t = a[i];",
        "  a[i] = a[j];",
        "  a[j] = t;",
        "}",
        "",
        "for (let i = 0; i < n - 1; i++) {                    // 依次填好第 i 个位置",
        "  let m = i;                                         // m 追踪未排序区间的最小值",
        "  for (let j = i + 1; j < n; j++) {",
        "    cmp++;                                           // 扫描未排序区间",
        "    if (a[j] < a[m]) m = j;                          // 找到更小的就更新 m",
        "  }",
        "  if (m !== i) {                                     // 最小值不在首位才交换",
        "    const t = a[i]; a[i] = a[m]; a[m] = t;",
        "    swp++; wrt += 2;",
        "  }",
        "  sorted.add(i);                                     // 第 i 位就位",
        "}",
        "report(a, n, cmp, swp, wrt);",
      ],
      steps: {
        swap: 19,
        mark: 22,
      },
    },
    py: {
      code: [
        "n = len(ARR)",
        "a = list(ARR)                                        # 复制一份，不改动原数组",
        "cmp = swp = wrt = 0",
        "sorted_pos = set()                                   # 已排定的位置",
        "",
        "def swap(i, j):",
        "    a[i], a[j] = a[j], a[i]",
        "",
        "for i in range(n - 1):                               # 依次填好第 i 个位置",
        "    m = i                                            # m 追踪未排序区间的最小值",
        "    for j in range(i + 1, n):",
        "        cmp += 1                                     # 扫描未排序区间",
        "        if a[j] < a[m]:",
        "            m = j                                    # 找到更小的就更新 m",
        "    if m != i:                                       # 最小值不在首位才交换",
        "        a[i], a[m] = a[m], a[i]",
        "        swp += 1; wrt += 2",
        "    sorted_pos.add(i)                                # 第 i 位就位",
        "report(a, cmp, swp, wrt)",
      ],
      steps: {
        swap: 16,
        mark: 18,
      },
    },
    c: {
      code: [
        "int n = ARR[0];",
        "int a[MAX];",
        "for (int i = 0; i < n; i++) a[i] = ARR[i + 1];",
        "int cmp = 0, swp = 0, wrt = 0;",
        "",
        "static void swap(int i, int j){                      /* 交换两个元素 */",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "static void pos_report(int i){                       /* 动画用的位置标记 */",
        '    printf("pos %d\\n", i);',
        "}",
        "",
        "for (int i = 0; i < n - 1; i++) {                    /* 依次填好第 i 个位置 */",
        "    int m = i;                                       /* m 追踪未排序区间的最小值 */",
        "    for (int j = i + 1; j < n; j++) {",
        "        cmp++;                                       /* 扫描未排序区间 */",
        "        if (a[j] < a[m]) m = j;                      /* 找到更小的就更新 m */",
        "    }",
        "    if (m != i) {                                    /* 最小值不在首位才交换 */",
        "        swap(i, m);",
        "        swp++; wrt += 2;",
        "    }",
        '    printf("pos %d\\n", i);                          /* 第 i 位就位 */',
        "}",
        'printf("%d %d %d\\n", cmp, swp, wrt);',
      ],
      steps: {
        swap: 23,
        mark: 26,
      },
    },
    java: {
      code: [
        "static void swap(int[] a, int i, int j){              // 交换两个元素",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "public static void main(String[] args){",
        "    int n = ARR.length;",
        "    int[] a = ARR.clone();                           // 复制一份",
        "",
        "    for (int i = 0; i < n - 1; i++) {                // 依次填好第 i 个位置",
        "        int m = i;                                   // m 追踪未排序区间的最小值",
        "        for (int j = i + 1; j < n; j++) {",
        "            cmp++;                                   // 扫描未排序区间",
        "            if (a[j] < a[m]) m = j;                  // 找到更小的就更新 m",
        "        }",
        "        if (m != i) {                                // 最小值不在首位才交换",
        "            swap(a, i, m);",
        "            swp++; wrt += 2;",
        "        }",
        "        sortedPos.add(i);                            // 第 i 位就位",
        "    }",
        "    report(a, n, cmp, swp, wrt);",
      ],
      steps: {
        swap: 18,
        mark: 21,
      },
    },
  },
  shell: {
    js: {
      code: [
        "const n = ARR.length;",
        "let cmp = 0, swp = 0, wrt = 0;",
        "const a = ARR.slice();                               // 复制一份，不改动原数组",
        "const sorted = new Set();                            // 已排定的位置",
        "",
        "function swap(i, j) {                                // 交换两个元素",
        "  const t = a[i];",
        "  a[i] = a[j];",
        "  a[j] = t;",
        "}",
        "",
        "const GAPS = [701, 301, 132, 57, 23, 10, 4, 1];      // Ciura 增量序列",
        "for (let g = 0; g < GAPS.length; g++) {              // 由大到小逐步缩小增量",
        "  const gap = GAPS[g];",
        "  if (gap >= n) continue;                            // 增量不能超过数组长度",
        "  for (let i = gap; i < n; i++) {",
        "    let j = i;",
        "    while (j >= gap) {",
        "      cmp++;                                         // 比较相隔 gap 的两个元素",
        "      if (a[j - gap] > a[j]) {                       // 相隔 gap 的逆序对",
        "        const t = a[j]; a[j] = a[j - gap]; a[j - gap] = t;",
        "        swp++; wrt += 2;                             // 跨 gap 交换，大步后移",
        "        j -= gap;",
        "      } else break;",
        "    }",
        "    if (j >= gap) wrt += 0;                          // 该组内已就位",
        "  }",
        "}",
        "report(a, n, cmp, swp, wrt);",
      ],
      steps: {
        gap: 16,
        shift: 21,
        put: 26,
      },
    },
    py: {
      code: [
        "n = len(ARR)",
        "a = list(ARR)                                        # 复制一份，不改动原数组",
        "cmp = swp = wrt = 0",
        "sorted_pos = set()                                   # 已排定的位置",
        "",
        "def swap(i, j):",
        "    a[i], a[j] = a[j], a[i]",
        "",
        "GAPS = [701, 301, 132, 57, 23, 10, 4, 1]             # Ciura 增量序列",
        "for gap in GAPS:                                     # 由大到小逐步缩小增量",
        "    if gap >= n:                                     # 增量不能超过数组长度",
        "        continue",
        "    for i in range(gap, n):",
        "        j = i",
        "        while j >= gap:",
        "            cmp += 1                                 # 比较相隔 gap 的两个元素",
        "            if a[j - gap] > a[j]:                    # 相隔 gap 的逆序对",
        "                a[j], a[j - gap] = a[j - gap], a[j]",
        "                swp += 1; wrt += 2                   # 跨 gap 交换，大步后移",
        "                j -= gap",
        "            else:",
        "                break",
        "        if j >= gap: wrt += 0                    # 该组内已就位",
        "report(a, cmp, swp, wrt)",
      ],
      steps: {
        gap: 13,
        shift: 18,
        put: 23,
      },
    },
    c: {
      code: [
        "int n = ARR[0];",
        "int a[MAX];",
        "for (int i = 0; i < n; i++) a[i] = ARR[i + 1];",
        "int cmp = 0, swp = 0, wrt = 0;",
        "",
        "static void swap(int i, int j){                      /* 交换两个元素 */",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "static void pos_report(int i){                       /* 动画用的位置标记 */",
        '    printf("pos %d\\n", i);',
        "}",
        "",
        "int GAPS[8] = {701, 301, 132, 57, 23, 10, 4, 1};    /* Ciura 增量序列 */",
        "for (int g = 0; g < 8; g++) {                        /* 由大到小逐步缩小增量 */",
        "    int gap = GAPS[g];",
        "    if (gap >= n) continue;                          /* 增量不能超过数组长度 */",
        "    for (int i = gap; i < n; i++) {",
        "        int j = i;",
        "        while (j >= gap) {",
        "            cmp++;                                   /* 比较相隔 gap 的两个元素 */",
        "            if (a[j - gap] > a[j]) {                 /* 相隔 gap 的逆序对 */",
        "                swap(j, j - gap);",
        "                swp++; wrt += 2;                     /* 跨 gap 交换，大步后移 */",
        "                j -= gap;",
        "            } else break;",
        "        }",
        "        if (j >= gap) wrt += 0;                      /* 该组内已就位 */",
        "    }",
        "}",
        'printf("%d %d %d\\n", cmp, swp, wrt);',
      ],
      steps: {
        gap: 20,
        shift: 25,
        put: 30,
      },
    },
    java: {
      code: [
        "static void swap(int[] a, int i, int j){              // 交换两个元素",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "public static void main(String[] args){",
        "    int n = ARR.length;",
        "    int[] a = ARR.clone();                           // 复制一份",
        "",
        "    int[] GAPS = {701, 301, 132, 57, 23, 10, 4, 1};  // Ciura 增量序列",
        "    for (int g = 0; g < GAPS.length; g++) {          // 由大到小逐步缩小增量",
        "        int gap = GAPS[g];",
        "        if (gap >= n) continue;                      // 增量不能超过数组长度",
        "        for (int i = gap; i < n; i++) {",
        "            int j = i;",
        "            while (j >= gap) {",
        "                cmp++;                               // 比较相隔 gap 的两个元素",
        "                if (a[j - gap] > a[j]) {             // 相隔 gap 的逆序对",
        "                    swap(a, j, j - gap);",
        "                    swp++; wrt += 2;                 // 跨 gap 交换，大步后移",
        "                    j -= gap;",
        "                } else break;",
        "            }",
        "            if (j >= gap) wrt += 0;                  // 该组内已就位",
        "        }",
        "    }",
        '    System.out.println(cmp + " " + swp + " " + wrt);',
      ],
      steps: {
        gap: 15,
        shift: 20,
        put: 25,
      },
    },
  },
  merge: {
    js: {
      code: [
        "const n = ARR.length;",
        "let cmp = 0, swp = 0, wrt = 0;",
        "const a = ARR.slice();                               // 复制一份，不改动原数组",
        "const sorted = new Set();                            // 已排定的位置",
        "",
        "function swap(i, j) {                                // 交换两个元素",
        "  const t = a[i];",
        "  a[i] = a[j];",
        "  a[j] = t;",
        "}",
        "",
        "function mergeSort(lo, hi) {                          // 排序左闭右开区间 [lo, hi)",
        "  if (hi - lo < 2) return;                           // 长度 0 或 1 天然有序",
        "  const mid = (lo + hi) >> 1;                        // 拆分成两半",
        "  mergeSort(lo, mid);                                // 递归排序左半",
        "  mergeSort(mid, hi);                                // 递归排序右半",
        "  let i = lo, j = mid, k = lo;",
        "  while (i < mid && j < hi) {                        // 合并两段有序序列",
        "    cmp++;                                           // 比较两段的头部",
        "    if (a[i] <= a[j]) buf[k++] = a[i++];             // 取较小者，保证稳定",
        "    else              buf[k++] = a[j++];",
        "    wrt++;",
        "  }",
        "  while (i < mid) buf[k++] = a[i++];                 // 收尾：左段剩余",
        "  while (j < hi)  buf[k++] = a[j++];                 // 收尾：右段剩余",
        "  for (let t = lo; t < hi; t++) a[t] = buf[t];       // 缓冲区整体写回主数组",
        "}",
        "buf = new Array(Math.max(n, 1)).fill(0);",
        "mergeSort(0, n);",
        "report(a, n, cmp, swp, wrt);",
      ],
      steps: {
        split: 14,
        left: 15,
        right: 16,
        pick: 20,
        back: 26,
      },
    },
    py: {
      code: [
        "n = len(ARR)",
        "a = list(ARR)                                        # 复制一份，不改动原数组",
        "cmp = swp = wrt = 0",
        "sorted_pos = set()                                   # 已排定的位置",
        "",
        "def swap(i, j):",
        "    a[i], a[j] = a[j], a[i]",
        "",
        "def merge_sort(a, buf, lo, hi, cmp, swp, wrt):       # 排序左闭右开区间 [lo, hi)",
        "    if hi - lo < 2:                                  # 长度 0 或 1 天然有序",
        "        return cmp, swp, wrt",
        "    mid = (lo + hi) // 2                             # 拆分成两半",
        "    cmp, swp, wrt = merge_sort(a, buf, lo, mid, cmp, swp, wrt)   # 递归排序左半",
        "    cmp, swp, wrt = merge_sort(a, buf, mid, hi, cmp, swp, wrt)   # 递归排序右半",
        "    i, j, k = lo, mid, lo",
        "    while i < mid and j < hi:                        # 合并两段有序序列",
        "        cmp += 1                                     # 比较两段的头部",
        "        if a[i] <= a[j]:                             # 取较小者，保证稳定",
        "            buf[k] = a[i]; i += 1",
        "        else:",
        "            buf[k] = a[j]; j += 1",
        "        k += 1; wrt += 1",
        "    while i < mid:",
        "        buf[k] = a[i]; i += 1; k += 1                # 收尾：左段剩余",
        "    while j < hi:",
        "        buf[k] = a[j]; j += 1; k += 1                # 收尾：右段剩余",
        "    for t in range(lo, hi):",
        "        a[t] = buf[t]                                # 缓冲区整体写回主数组",
        "    return cmp, swp, wrt",
        "buf = [0] * max(n, 1)",
        "cmp, swp, wrt = merge_sort(a, buf, 0, n, cmp, swp, wrt)",
        "report(a, cmp, swp, wrt)",
      ],
      steps: {
        split: 12,
        left: 13,
        right: 14,
        pick: 18,
        back: 27,
      },
    },
    c: {
      code: [
        "int n = ARR[0];",
        "int a[MAX];",
        "for (int i = 0; i < n; i++) a[i] = ARR[i + 1];",
        "int cmp = 0, swp = 0, wrt = 0;",
        "",
        "static void swap(int i, int j){                      /* 交换两个元素 */",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "static void pos_report(int i){                       /* 动画用的位置标记 */",
        '    printf("pos %d\\n", i);',
        "}",
        "",
        "static void merge_sort(int lo, int hi) {             /* 排序左闭右开区间 [lo, hi) */",
        "    if (hi - lo < 2) return;                         /* 长度 0 或 1 天然有序 */",
        "    int mid = (lo + hi) / 2;                         /* 拆分成两半 */",
        "    merge_sort(lo, mid);                             /* 递归排序左半 */",
        "    merge_sort(mid, hi);                             /* 递归排序右半 */",
        "    int i = lo, j = mid, k = lo;",
        "    while (i < mid && j < hi) {                      /* 合并两段有序序列 */",
        "        cmp++;                                       /* 比较两段的头部 */",
        "        if (a[i] <= a[j]) buf[k++] = a[i++];         /* 取较小者，保证稳定 */",
        "        else              buf[k++] = a[j++];",
        "        wrt++;",
        "    }",
        "    while (i < mid) buf[k++] = a[i++];               /* 收尾：左段剩余 */",
        "    while (j < hi)  buf[k++] = a[j++];               /* 收尾：右段剩余 */",
        "    for (int t = lo; t < hi; t++) a[t] = buf[t];     /* 缓冲区整体写回主数组 */",
        "}",
        "merge_sort(0, n);",
        'printf("%d %d %d\\n", cmp, swp, wrt);',
      ],
      steps: {
        split: 18,
        left: 19,
        right: 20,
        pick: 24,
        back: 30,
      },
    },
    java: {
      code: [
        "static void swap(int[] a, int i, int j){              // 交换两个元素",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "public static void main(String[] args){",
        "    int n = ARR.length;",
        "    int[] a = ARR.clone();                           // 复制一份",
        "",
        "    mergeSort(a, 0, n);",
        "    report(a, n, cmp, swp, wrt);",
        "}",
        "",
        "static void mergeSort(int[] a, int lo, int hi) {     // 排序左闭右开区间 [lo, hi)",
        "    if (hi - lo < 2) return;                         // 长度 0 或 1 天然有序",
        "    int mid = (lo + hi) >>> 1;                       // 拆分成两半",
        "    mergeSort(a, lo, mid);                           // 递归排序左半",
        "    mergeSort(a, mid, hi);                           // 递归排序右半",
        "    int i = lo, j = mid, k = lo;",
        "    while (i < mid && j < hi) {                      // 合并两段有序序列",
        "        cmp++;                                       // 比较两段的头部",
        "        if (a[i] <= a[j]) buf[k++] = a[i++];         // 取较小者，保证稳定",
        "        else              buf[k++] = a[j++];",
        "        wrt++;",
        "    }",
        "    while (i < mid) buf[k++] = a[i++];               // 收尾：左段剩余",
        "    while (j < hi)  buf[k++] = a[j++];               // 收尾：右段剩余",
        "    for (int t = lo; t < hi; t++) a[t] = buf[t];     // 缓冲区整体写回主数组",
        "}",
      ],
      steps: {
        split: 17,
        left: 18,
        right: 19,
        pick: 23,
        back: 29,
      },
    },
  },
  quick: {
    js: {
      code: [
        "const n = ARR.length;",
        "let cmp = 0, swp = 0, wrt = 0;",
        "const a = ARR.slice();                               // 复制一份，不改动原数组",
        "const sorted = new Set();                            // 已排定的位置",
        "",
        "function swap(i, j) {                                // 交换两个元素",
        "  const t = a[i];",
        "  a[i] = a[j];",
        "  a[j] = t;",
        "}",
        "",
        "function quickSort(lo, hi) {",
        "  if (lo >= hi) return;                              // 长度 0 或 1 天然有序",
        "  const mid = (lo + hi) >> 1;",
        "  if (a[mid] < a[lo]) { const t = a[mid]; a[mid] = a[lo]; a[lo] = t; }   // 三数取中",
        "  if (a[hi]  < a[lo]) { const t = a[hi];  a[hi]  = a[lo]; a[lo] = t; }",
        "  if (a[hi]  < a[mid]) { const t = a[hi]; a[hi] = a[mid]; a[mid] = t; }",
        "  const p = a[mid];                                  // pivot = 三数中位数",
        "  let i = lo, j = hi;",
        "  while (i <= j) {",
        "    while (a[i] < p) i++;                            // 左侧找到 ≥ pivot 的元素",
        "    while (a[j] > p) j--;                            // 右侧找到 ≤ pivot 的元素",
        "    if (i <= j) {",
        "      const t = a[i]; a[i] = a[j]; a[j] = t;",
        "      swp++; wrt += 2; i++; j--;",
        "    }",
        "  }",
        "  quickSort(lo, j); quickSort(i, hi);                // 递归左右两段",
        "}",
        "quickSort(0, n - 1);",
        "report(a, n, cmp, swp, wrt);",
      ],
      steps: {
        pivot: 18,
        left: 21,
        right: 22,
        swap: 24,
        split: 28,
        recurse: 28,
      },
    },
    py: {
      code: [
        "n = len(ARR)",
        "a = list(ARR)                                        # 复制一份，不改动原数组",
        "cmp = swp = wrt = 0",
        "sorted_pos = set()                                   # 已排定的位置",
        "",
        "def swap(i, j):",
        "    a[i], a[j] = a[j], a[i]",
        "",
        "def quick_sort(a, lo, hi, cmp, swp, wrt):",
        "    if lo >= hi:                                     # 长度 0 或 1 天然有序",
        "        return cmp, swp, wrt",
        "    mid = (lo + hi) // 2",
        "    if a[mid] < a[lo]: a[lo], a[mid] = a[mid], a[lo]      # 三数取中",
        "    if a[hi]  < a[lo]: a[lo], a[hi]  = a[hi],  a[lo]",
        "    if a[hi]  < a[mid]: a[mid], a[hi] = a[hi], a[mid]",
        "    p = a[mid]                                       # pivot = 三数中位数",
        "    i, j = lo, hi",
        "    while i <= j:",
        "        while a[i] < p:",
        "            i += 1                                   # 左侧找到 ≥ pivot 的元素",
        "        while a[j] > p:",
        "            j -= 1                                   # 右侧找到 ≤ pivot 的元素",
        "        if i <= j:",
        "            a[i], a[j] = a[j], a[i]",
        "            swp += 1; wrt += 2; i += 1; j -= 1",
        "    cmp, swp, wrt = quick_sort(a, lo, j, cmp, swp, wrt)",
        "    cmp, swp, wrt = quick_sort(a, i, hi, cmp, swp, wrt)   # 递归左右两段",
        "    return cmp, swp, wrt",
        "cmp, swp, wrt = quick_sort(a, 0, n - 1, cmp, swp, wrt)",
        "report(a, cmp, swp, wrt)",
      ],
      steps: {
        pivot: 16,
        left: 19,
        right: 21,
        swap: 24,
        split: 26,
        recurse: 27,
      },
    },
    c: {
      code: [
        "int n = ARR[0];",
        "int a[MAX];",
        "for (int i = 0; i < n; i++) a[i] = ARR[i + 1];",
        "int cmp = 0, swp = 0, wrt = 0;",
        "",
        "static void swap(int i, int j){                      /* 交换两个元素 */",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "static void pos_report(int i){                       /* 动画用的位置标记 */",
        '    printf("pos %d\\n", i);',
        "}",
        "",
        "static void quick_sort(int lo, int hi) {",
        "    if (lo >= hi) return;                            /* 长度 0 或 1 天然有序 */",
        "    int mid = (lo + hi) / 2;",
        "    if (a[mid] < a[lo]) swap(lo, mid);               /* 三数取中 */",
        "    if (a[hi]  < a[lo]) swap(lo, hi);",
        "    if (a[hi]  < a[mid]) swap(mid, hi);",
        "    int p = a[mid];                                  /* pivot = 三数中位数 */",
        "    int i = lo, j = hi;",
        "    while (i <= j) {",
        "        while (a[i] < p) i++;                        /* 左侧找到 ≥ pivot 的元素 */",
        "        while (a[j] > p) j--;                        /* 右侧找到 ≤ pivot 的元素 */",
        "        if (i <= j) {",
        "            swap(i, j);",
        "            swp++; wrt += 2; i++; j--;",
        "        }",
        "    }",
        "    quick_sort(lo, j); quick_sort(i, hi);            /* 递归左右两段 */",
        "}",
        "quick_sort(0, n - 1);",
        'printf("%d %d %d\\n", cmp, swp, wrt);',
      ],
      steps: {
        pivot: 22,
        left: 25,
        right: 26,
        swap: 28,
        split: 32,
        recurse: 32,
      },
    },
    java: {
      code: [
        "static void swap(int[] a, int i, int j){              // 交换两个元素",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "public static void main(String[] args){",
        "    int n = ARR.length;",
        "    int[] a = ARR.clone();                           // 复制一份",
        "",
        "    quickSort(a, 0, n - 1);",
        "    report(a, n, cmp, swp, wrt);",
        "}",
        "",
        "static void quickSort(int[] a, int lo, int hi) {",
        "    if (lo >= hi) return;                            // 长度 0 或 1 天然有序",
        "    int mid = (lo + hi) >>> 1;",
        "    if (a[mid] < a[lo]) swap(a, lo, mid);            // 三数取中",
        "    if (a[hi]  < a[lo]) swap(a, lo, hi);",
        "    if (a[hi]  < a[mid]) swap(a, mid, hi);",
        "    int p = a[mid];                                  // pivot = 三数中位数",
        "    int i = lo, j = hi;",
        "    while (i <= j) {",
        "        while (a[i] < p) i++;                        // 左侧找到 ≥ pivot 的元素",
        "        while (a[j] > p) j--;                        // 右侧找到 ≤ pivot 的元素",
        "        if (i <= j) {",
        "            swap(a, i, j);",
        "            swp++; wrt += 2; i++; j--;",
        "        }",
        "    }",
        "    quickSort(a, lo, j); quickSort(a, i, hi);        // 递归左右两段",
        "}",
      ],
      steps: {
        pivot: 21,
        left: 24,
        right: 25,
        swap: 27,
        split: 31,
        recurse: 31,
      },
    },
  },
  heap: {
    js: {
      code: [
        "const n = ARR.length;",
        "let cmp = 0, swp = 0, wrt = 0;",
        "const a = ARR.slice();                               // 复制一份，不改动原数组",
        "const sorted = new Set();                            // 已排定的位置",
        "",
        "function swap(i, j) {                                // 交换两个元素",
        "  const t = a[i];",
        "  a[i] = a[j];",
        "  a[j] = t;",
        "}",
        "",
        "function sift(root, end) {                            // 让 a[root] 在 [0, end] 内下沉",
        "  while (true) {",
        "    let child = root * 2 + 1;                         // 左孩子下标",
        "    if (child > end) break;",
        "    if (child + 1 <= end) { cmp++; if (a[child] < a[child + 1]) child++; }",
        "    cmp++;                                            // 父节点与较大孩子比较",
        "    if (a[root] < a[child]) {                         // 父 < 子 → 违反大顶堆",
        "      const t = a[root]; a[root] = a[child]; a[child] = t;",
        "      swp++; wrt += 2; root = child;",
        "    } else break;                                     // 已满足堆性质",
        "  }",
        "  return;",
        "}",
        "for (let i = (n - 2) >> 1; i >= 0; i--) sift(i, n - 1);   // 阶段一：建大顶堆",
        "for (let end = n - 1; end > 0; end--) {",
        "  const t = a[0]; a[0] = a[end]; a[end] = t;          // 堆顶最大值换到末尾",
        "  swp++; wrt += 2;",
        "  sorted.add(end);",
        "  if (end - 1 > 0) sift(0, end - 1);                  // 阶段二：缩小堆并重新下沉",
        "}",
        "report(a, n, cmp, swp, wrt);",
      ],
      steps: {
        siftcmp: 18,
        siftend: 23,
        build: 25,
        swap: 27,
        mark: 29,
      },
    },
    py: {
      code: [
        "n = len(ARR)",
        "a = list(ARR)                                        # 复制一份，不改动原数组",
        "cmp = swp = wrt = 0",
        "sorted_pos = set()                                   # 已排定的位置",
        "",
        "def swap(i, j):",
        "    a[i], a[j] = a[j], a[i]",
        "",
        "def sift(a, root, end, cmp, swp, wrt):                # 让 a[root] 在 [0, end] 内下沉",
        "    while True:",
        "        child = root * 2 + 1                          # 左孩子下标",
        "        if child > end:",
        "            break",
        "        if child + 1 <= end:",
        "            cmp += 1",
        "            if a[child] < a[child + 1]:",
        "                child += 1",
        "        cmp += 1                                      # 父节点与较大孩子比较",
        "        if a[root] < a[child]:                        # 父 < 子 → 违反大顶堆",
        "            a[root], a[child] = a[child], a[root]",
        "            swp += 1; wrt += 2; root = child",
        "        else:",
        "            break                                     # 已满足堆性质",
        "    return cmp, swp, wrt",
        "for i in range((n - 2) // 2, -1, -1):                 # 阶段一：建大顶堆",
        "    cmp, swp, wrt = sift(a, i, n - 1, cmp, swp, wrt)",
        "for end in range(n - 1, 0, -1):",
        "    a[0], a[end] = a[end], a[0]                       # 堆顶最大值换到末尾",
        "    swp += 1; wrt += 2",
        "    sorted_pos.add(end)",
        "    if end - 1 > 0:",
        "        cmp, swp, wrt = sift(a, 0, end - 1, cmp, swp, wrt)   # 阶段二：缩小堆并重新下沉",
        "report(a, cmp, swp, wrt)",
      ],
      steps: {
        siftcmp: 19,
        siftend: 24,
        build: 25,
        swap: 28,
        mark: 30,
      },
    },
    c: {
      code: [
        "int n = ARR[0];",
        "int a[MAX];",
        "for (int i = 0; i < n; i++) a[i] = ARR[i + 1];",
        "int cmp = 0, swp = 0, wrt = 0;",
        "",
        "static void swap(int i, int j){                      /* 交换两个元素 */",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "static void pos_report(int i){                       /* 动画用的位置标记 */",
        '    printf("pos %d\\n", i);',
        "}",
        "",
        "static void sift(int root, int end) {                 /* 让 a[root] 在 [0, end] 内下沉 */",
        "    while (1) {",
        "        int child = root * 2 + 1;                     /* 左孩子下标 */",
        "        if (child > end) break;",
        "        if (child + 1 <= end) {           // 孩子中取较大的那个",
        "            cmp++;",
        "            if (a[child] < a[child + 1]) child++;",
        "        }",
        "        cmp++;                                        /* 父节点与较大孩子比较 */",
        "        if (a[root] < a[child]) {                     /* 父 < 子 → 违反大顶堆 */",
        "            swap(root, child);",
        "            swp++; wrt += 2; root = child;",
        "        } else break;                                 /* 已满足堆性质 */",
        "    }",
        "    return;",
        "}",
        "for (int i = (n - 2) / 2; i >= 0; i--) sift(i, n - 1);   /* 阶段一：建大顶堆 */",
        "for (int end = n - 1; end > 0; end--) {",
        "    swap(0, end);                                     /* 堆顶最大值换到末尾 */",
        "    swp++; wrt += 2;",
        '    printf("pos %d\\n", end);',
        "    if (end - 1 > 0) sift(0, end - 1);                /* 阶段二：缩小堆并重新下沉 */",
        "}",
        'printf("%d %d %d\\n", cmp, swp, wrt);',
      ],
      steps: {
        siftcmp: 25,
        siftend: 30,
        build: 32,
        swap: 34,
        mark: 36,
      },
    },
    java: {
      code: [
        "static void swap(int[] a, int i, int j){              // 交换两个元素",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "public static void main(String[] args){",
        "    int n = ARR.length;",
        "    int[] a = ARR.clone();                           // 复制一份",
        "",
        "    heapSort(a, n);",
        "    report(a, n, cmp, swp, wrt);",
        "}",
        "",
        "static void heapSort(int[] a, int n) {",
        "    // 阶段一：建大顶堆",
        "    for (int i = (n - 2) / 2; i >= 0; i--)",
        "        sift(a, i, n - 1);",
        "    for (int end = n - 1; end > 0; end--) {",
        "        swap(a, 0, end);                              // 堆顶最大值换到末尾",
        "        swp++; wrt += 2;",
        "        sortedPos.add(end);",
        "        if (end - 1 > 0) sift(a, 0, end - 1);         // 阶段二：缩小堆并重新下沉",
        "    }",
        "}",
        "",
        "static void sift(int[] a, int root, int end) {        // 让 a[root] 在 [0, end] 内下沉",
        "    while (true) {",
        "        int child = root * 2 + 1;                     // 左孩子下标",
        "        if (child > end) break;",
        "        if (child + 1 <= end) {           // 孩子中取较大的那个",
        "            cmp++;",
        "            if (a[child] < a[child + 1]) child++;",
        "        }",
        "        cmp++;                                        // 父节点与较大孩子比较",
        "        if (a[root] < a[child]) {                     // 父 < 子 → 违反大顶堆",
        "            swap(a, root, child);",
        "            swp++; wrt += 2; root = child;",
        "        } else break;                                 // 已满足堆性质",
        "    }",
        "}",
      ],
      steps: {
        build: 16,
        swap: 20,
        mark: 22,
        siftcmp: 36,
        siftend: 41,
      },
    },
  },
  radix: {
    js: {
      code: [
        "const n = ARR.length;",
        "let cmp = 0, swp = 0, wrt = 0;",
        "const a = ARR.slice();                               // 复制一份，不改动原数组",
        "const sorted = new Set();                            // 已排定的位置",
        "",
        "function swap(i, j) {                                // 交换两个元素",
        "  const t = a[i];",
        "  a[i] = a[j];",
        "  a[j] = t;",
        "}",
        "",
        "let mx = 0; for (const v of a) if (v > mx) mx = v;",
        "const digits = String(mx).length;                     // 最大值的位数 = 需要几轮",
        "for (let d = 0; d < digits; d++) {                    // 从个位开始，逐位分发",
        "  const buckets = Array.from({ length: 10 }, () => []);",
        "  for (let i = 0; i < n; i++) {",
        "    const dig = Math.floor(a[i] / 10 ** d) % 10;      // 取第 d 位数字",
        "    buckets[dig].push(a[i]); wrt++;                   // 分发进对应的桶",
        "  }",
        "  let k = 0;",
        "  for (let b = 0; b < 10; b++) {                      // 按桶序 0→9 收回",
        "    for (const v of buckets[b]) {",
        "      a[k] = v; wrt++;                                // 桶内保持原序 → 稳定",
        "      k++;",
        "    }",
        "  }",
        "}",
        "report(a, n, cmp, swp, wrt);",
      ],
      steps: {
        digit: 13,
        bucket: 17,
        gather: 23,
        pass: 27,
      },
    },
    py: {
      code: [
        "n = len(ARR)",
        "a = list(ARR)                                        # 复制一份，不改动原数组",
        "cmp = swp = wrt = 0",
        "sorted_pos = set()                                   # 已排定的位置",
        "",
        "def swap(i, j):",
        "    a[i], a[j] = a[j], a[i]",
        "",
        "mx = max(a)",
        "digits = len(str(mx))                                 # 最大值的位数 = 需要几轮",
        "for d in range(digits):                               # 从个位开始，逐位分发",
        "    buckets = [[] for _ in range(10)]",
        "    for i in range(n):",
        "        dig = (a[i] // 10 ** d) % 10                  # 取第 d 位数字",
        "        buckets[dig].append(a[i]); wrt += 1           # 分发进对应的桶",
        "    k = 0",
        "    for b in range(10):                               # 按桶序 0→9 收回",
        "        for v in buckets[b]:",
        "            a[k] = v; wrt += 1                        # 桶内保持原序 → 稳定",
        "            k += 1",
        "report(a, cmp, swp, wrt)",
      ],
      steps: {
        digit: 10,
        bucket: 14,
        gather: 19,
        pass: 21,
      },
    },
    c: {
      code: [
        "int n = ARR[0];",
        "int a[MAX];",
        "for (int i = 0; i < n; i++) a[i] = ARR[i + 1];",
        "int cmp = 0, swp = 0, wrt = 0;",
        "",
        "static void swap(int i, int j){                      /* 交换两个元素 */",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "static void pos_report(int i){                       /* 动画用的位置标记 */",
        '    printf("pos %d\\n", i);',
        "}",
        "",
        "int mx = 0; for (int i = 0; i < n; i++) if (a[i] > mx) mx = a[i];",
        "int digits = 1; while (mx >= 10) { mx /= 10; digits++; }   /* 最大值的位数 */",
        "for (int d = 0; d < digits; d++) {                    /* 从个位开始，逐位分发 */",
        "    int cnt[10] = {0}, bucket[10][MAX];",
        "    for (int i = 0; i < n; i++) {",
        "        int pow = 1; for (int t = 0; t < d; t++) pow *= 10;",
        "        int dig = (a[i] / pow) % 10;                  /* 取第 d 位数字 */",
        "        bucket[dig][cnt[dig]++] = a[i]; wrt++;        /* 分发进对应的桶 */",
        "    }",
        "    int k = 0;",
        "    for (int b = 0; b < 10; b++) {                    /* 按桶序 0→9 收回 */",
        "        for (int q = 0; q < cnt[b]; q++) {",
        "            a[k] = bucket[b][q]; wrt++;               /* 桶内保持原序 → 稳定 */",
        "            k++;",
        "        }",
        "    }",
        "}",
        'printf("%d %d %d\\n", cmp, swp, wrt);',
      ],
      steps: {
        digit: 17,
        bucket: 21,
        gather: 28,
        pass: 32,
      },
    },
    java: {
      code: [
        "static void swap(int[] a, int i, int j){              // 交换两个元素",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "public static void main(String[] args){",
        "    int n = ARR.length;",
        "    int[] a = ARR.clone();                           // 复制一份",
        "",
        "    int mx = 0;",
        "    for (int v : a) if (v > mx) mx = v;",
        "    int digits = String.valueOf(mx).length();         // 最大值的位数 = 需要几轮",
        "    for (int d = 0; d < digits; d++) {                // 从个位开始，逐位分发",
        "        int[][] buckets = new int[10][n];",
        "        int[] cnt = new int[10];",
        "        for (int i = 0; i < n; i++) {",
        "            // 取第 d 位数字",
        "            int dig = (int)(a[i] / Math.pow(10, d)) % 10;",
        "            buckets[dig][cnt[dig]++] = a[i];  // 分发进桶",
        "            wrt++;",
        "        }",
        "        int k = 0;",
        "        for (int b = 0; b < 10; b++) {                // 按桶序 0→9 收回",
        "            for (int q = 0; q < cnt[b]; q++) {",
        "                a[k] = buckets[b][q]; wrt++;          // 桶内保持原序 → 稳定",
        "                k++;",
        "            }",
        "        }",
        "    }",
        "    report(a, n, cmp, swp, wrt);",
      ],
      steps: {
        digit: 13,
        bucket: 18,
        gather: 26,
        pass: 30,
      },
    },
  },
  cocktail: {
    js: {
      code: [
        "const n = ARR.length;",
        "let cmp = 0, swp = 0, wrt = 0;",
        "const a = ARR.slice();                               // 复制一份，不改动原数组",
        "const sorted = new Set();                            // 已排定的位置",
        "",
        "function swap(i, j) {                                // 交换两个元素",
        "  const t = a[i];",
        "  a[i] = a[j];",
        "  a[j] = t;",
        "}",
        "",
        "let lo = 0, hi = n - 1;",
        "while (lo < hi) {                                     // 未排序区间 [lo, hi]",
        "  let swapped = false;",
        "  for (let i = lo; i < hi; i++) {                     // → 向右扫描",
        "    cmp++;",
        "    if (a[i] > a[i + 1]) {                            // 把最大值推向 hi",
        "      const t = a[i]; a[i] = a[i + 1]; a[i + 1] = t;",
        "      swp++; wrt += 2; swapped = true;",
        "    }",
        "  }",
        "  sorted.add(hi); hi--;                               // 右端就位，区间右缩",
        "  for (let i = hi; i > lo; i--) {                     // ← 向左扫描",
        "    cmp++;",
        "    if (a[i] < a[i - 1]) {                            // 把最小值推向 lo",
        "      const t = a[i]; a[i] = a[i - 1]; a[i - 1] = t;",
        "      swp++; wrt += 2; swapped = true;",
        "    }",
        "  }",
        "  sorted.add(lo); lo++;                               // 左端就位，区间左缩",
        "  if (!swapped) break;                                // 整趟无交换 → 已有序",
        "}",
        "report(a, n, cmp, swp, wrt);",
      ],
      steps: {
        fwd: 18,
        markhi: 22,
        bwd: 26,
        marklo: 30,
      },
    },
    py: {
      code: [
        "n = len(ARR)",
        "a = list(ARR)                                        # 复制一份，不改动原数组",
        "cmp = swp = wrt = 0",
        "sorted_pos = set()                                   # 已排定的位置",
        "",
        "def swap(i, j):",
        "    a[i], a[j] = a[j], a[i]",
        "",
        "lo, hi = 0, n - 1",
        "while lo < hi:                                        # 未排序区间 [lo, hi]",
        "    swapped = False",
        "    for i in range(lo, hi):                           # → 向右扫描",
        "        cmp += 1",
        "        if a[i] > a[i + 1]:                           # 把最大值推向 hi",
        "            a[i], a[i + 1] = a[i + 1], a[i]",
        "            swp += 1; wrt += 2; swapped = True",
        "    sorted_pos.add(hi); hi -= 1                       # 右端就位，区间右缩",
        "    for i in range(hi, lo, -1):                       # ← 向左扫描",
        "        cmp += 1",
        "        if a[i] < a[i - 1]:                           # 把最小值推向 lo",
        "            a[i], a[i - 1] = a[i - 1], a[i]",
        "            swp += 1; wrt += 2; swapped = True",
        "    sorted_pos.add(lo); lo += 1                       # 左端就位，区间左缩",
        "    if not swapped:                                   # 整趟无交换 → 已有序",
        "        break",
        "report(a, cmp, swp, wrt)",
      ],
      steps: {
        fwd: 15,
        markhi: 17,
        bwd: 21,
        marklo: 23,
      },
    },
    c: {
      code: [
        "int n = ARR[0];",
        "int a[MAX];",
        "for (int i = 0; i < n; i++) a[i] = ARR[i + 1];",
        "int cmp = 0, swp = 0, wrt = 0;",
        "",
        "static void swap(int i, int j){                      /* 交换两个元素 */",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "static void pos_report(int i){                       /* 动画用的位置标记 */",
        '    printf("pos %d\\n", i);',
        "}",
        "",
        "int lo = 0, hi = n - 1;",
        "while (lo < hi) {                                     /* 未排序区间 [lo, hi] */",
        "    int swapped = 0;",
        "    for (int i = lo; i < hi; i++) {                   /* → 向右扫描 */",
        "        cmp++;",
        "        if (a[i] > a[i + 1]) {                        /* 把最大值推向 hi */",
        "            swap(i, i + 1);",
        "            swp++; wrt += 2; swapped = 1;",
        "        }",
        "    }",
        '    printf("pos %d\\n", hi); hi--;                    /* 右端就位，区间右缩 */',
        "    for (int i = hi; i > lo; i--) {                   /* ← 向左扫描 */",
        "        cmp++;",
        "        if (a[i] < a[i - 1]) {                        /* 把最小值推向 lo */",
        "            swap(i, i - 1);",
        "            swp++; wrt += 2; swapped = 1;",
        "        }",
        "    }",
        '    printf("pos %d\\n", lo); lo++;                    /* 左端就位，区间左缩 */',
        "    if (!swapped) break;                              /* 整趟无交换 → 已有序 */",
        "}",
        'printf("%d %d %d\\n", cmp, swp, wrt);',
      ],
      steps: {
        fwd: 22,
        markhi: 26,
        bwd: 30,
        marklo: 34,
      },
    },
    java: {
      code: [
        "static void swap(int[] a, int i, int j){              // 交换两个元素",
        "    int t = a[i];",
        "    a[i] = a[j];",
        "    a[j] = t;",
        "}",
        "",
        "public static void main(String[] args){",
        "    int n = ARR.length;",
        "    int[] a = ARR.clone();                           // 复制一份",
        "",
        "    int lo = 0, hi = n - 1;",
        "    while (lo < hi) {                                 // 未排序区间 [lo, hi]",
        "        boolean swapped = false;",
        "        for (int i = lo; i < hi; i++) {               // → 向右扫描",
        "            cmp++;",
        "            if (a[i] > a[i + 1]) {                    // 把最大值推向 hi",
        "                swap(a, i, i + 1);",
        "                swp++; wrt += 2; swapped = true;",
        "            }",
        "        }",
        "        sortedPos.add(hi); hi--;                      // 右端就位，区间右缩",
        "        for (int i = hi; i > lo; i--) {               // ← 向左扫描",
        "            cmp++;",
        "            if (a[i] < a[i - 1]) {                    // 把最小值推向 lo",
        "                swap(a, i, i - 1);",
        "                swp++; wrt += 2; swapped = true;",
        "            }",
        "        }",
        "        sortedPos.add(lo); lo++;                      // 左端就位，区间左缩",
        "        if (!swapped) break;                          // 整趟无交换 → 已有序",
        "    }",
        "    report(a, n, cmp, swp, wrt);",
      ],
      steps: {
        fwd: 17,
        markhi: 21,
        bwd: 25,
        marklo: 29,
      },
    },
  },
};

for (const [lang, pack] of Object.entries(LANGS.bubble))
  pack.steps.compare = pack.steps.swap - 1;
for (const pack of Object.values(LANGS.selection))
  pack.steps.compare = pack.steps.swap - 3;
for (const [lang, pack] of Object.entries(LANGS.shell)) {
  pack.steps.compare = pack.steps.shift - 1;
  pack.steps.gap -= lang === "py" ? 3 : 2;
}

export { LANGS };
